# base image conains the normal softwares
FROM index.qiniu.com/ataraxia/meterbase:v0.0.1
MAINTAINER cocodee <coco.dee@gmail.com>

RUN sed -i s/archive.ubuntu.com/mirrors.163.com/g /etc/apt/sources.list
RUN apt-get update
COPY a-electric-files/* /workspace/
RUN apt-get install -y libcv-dev
RUN apt-get install -y python-opencv  python-numpy vim
WORKDIR /workspace
CMD python ./server.py 
